### ISSUE TITLE
Get video URL only 

### ISSUE THREAD

**Issue by davemac** [airesvsg/acf-youtubepicker#1]
Thanks for the plugin, very helpful.

Is there a possibility of providing a [video-url] key, so I don't have to manipulate the [iframe] key to get the video URL?

**Comment by airesvsg** [comment]
Hi @davemac!
Thanks.

Yes, it's possible. Now you can also choose which keys the answers.

![ACF YouTube Picker Answer Options](http://airesgoncalves.com.br/youtubepicker/youtubepicer-answer-options.png)
