### ISSUE TITLE
Mixed Content Error when using the plugin on a https website

### ISSUE THREAD

**Issue by ucu2009** [airesvsg/acf-youtubepicker#16]
Everything work's fine on local and staging env(http), but when i try the plugin on production(https) i get an error like this:

> **Mixed Content: The page at** https://example.com **was loaded over HTTPS, but requested an insecure resource** 'http://www.youtube.com/embed...'. **This request has been blocked; the content must be served over HTTPS.**

I specify that this problem is only  when i search the video i want, and **click on preview button.**

Is there a setting where i can set to make the request over https?  or i have to manualy modify the plugin?

**Comment by airesvsg** [comment]
Hi @ucu2009,
In my [last commit](https://github.com/airesvsg/acf-youtubepicker/commit/1c7e1c869a6ef39c2c25dda0265e5e40373346f4) I fixed it.
I'm not updated the WordPress repository yet, please download the current version [here](https://github.com/airesvsg/acf-youtubepicker/releases/tag/3.2.0).
Thanks
