### ISSUE TITLE
Multiple videos in repeater field issue

### ISSUE THREAD

**Issue by davemac** [airesvsg/acf-youtubepicker#2]
Hi there,

I have acf-youtube picker field inside a repeater field.

When editing the page, if I create a second repeater field and start to select videos, the video I select is shown in the first repeater field as well as the second repeater field.

**Comment by airesvsg** [comment]
Hi @davemac,

I will soon be testing and making the necessary corrections. 

Thanks

**Comment by airesvsg** [comment]
Hi @davemac,
Fixed.

Cheers

**Comment by davemac** [comment]
This still seems to be happening for me. I've attached an export of my field group if that helps?

[acf-export-2015-12-17.txt](https://github.com/airesvsg/acf-youtubepicker/files/64956/acf-export-2015-12-17.txt)

**Comment by airesvsg** [comment]
I think it's helps.
What version of the repeater plugin?

**Comment by davemac** [comment]
I'm using ACF Pro, latest version  5.3.2.2. The repeater field is part of ACF Pro.

**Comment by airesvsg** [comment]
OK, I'll check it.

**Comment by davemac** [comment]
Hi there, wondering if you have managed to resolve this issue at all?

**Comment by airesvsg** [comment]
Hi @davemac,
can you send your project to me?
airesvsg@gmail.com
