### ISSUE TITLE
Instruction on using the advanced options

### ISSUE THREAD

**Issue by sarukuku** [airesvsg/acf-youtubepicker#3]
First, thank you for this plugin. Very useful & user friendly.

The plugin has a lot of options if you consider the advanced options too. I'm struggling to understand what some of the advanced options do. It would be nice if the readme would have short descriptions for what each option field does / affects to.

I'm now struggling in restricting the search to a channel scope. I've obtained the channel ID and pasted it in the Channel ID field under the advanced options but the search still isn't restricted to videos on that channel. Any tips what I'm doing wrong? Is the API key related to this in some way?

**Comment by airesvsg** [comment]
Hi @sarukuku,

You can find an explanation to all parameters in below url:
https://developers.google.com/youtube/v3/docs/search/list#params

Maybe it's a bug in the plugin [YouTube Picker](https://github.com/airesvsg/youtubepicker). I'll check in soon.

Thanks

**Comment by fgilio** [comment]
Hi @airesvsg!

I had the same problem with the Channel ID, I would be nice if you can fix it.

Thanks!

**Comment by sarukuku** [comment]
@airesvsg that would be awesome! We're preparing a site launch where this plugin has been used. And thanks for the link!

**Comment by sarukuku** [comment]
Tested, works. Superb. Thanks @airesvsg!

**Comment by airesvsg** [comment]
:smile::+1:
